# Generated by Django 4.2 on 2024-08-08 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('type', models.CharField(choices=[('VALLENATO', 'VALLENATO'), ('CUMBIA', 'CUMBIA'), ('ELECTRONICA', 'ELECTRONICA'), ('ROCK', 'ROCK'), ('BACHATA', 'BACHATA')], max_length=30)),
                ('picture', models.ImageField(upload_to='album_images')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_manager.artista')),
            ],
        ),
    ]
